package com.bigdeal.entity;
// Generated Sep 19, 2020 3:34:09 PM by Hibernate Tools 5.4.18.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductRating generated by hbm2java
 */
@Entity
@Table(name = "product_rating")
public class ProductRating implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "id", nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	@Column(name = "user_name", length = 50)
	private String userName;
	@Column(name = "product_code", length = 50)
	private String productCode;
//	@Column(name = "product_code", length = 50)
//	private String productCode;
	@Column(name = "rating")
	private short rating;
	@Column(name = "message")
	private String message;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at")
	private Date createdAt;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at")
	private Date updatedAt;

	public ProductRating() {
	}

	public ProductRating(String userName, String productCode, short rating, String message) {
		this.userName = userName;
		this.productCode = productCode;
		this.rating = rating;
		this.message = message;
	}

	public ProductRating(String userName, String productCode, short rating, String message, Date createdAt,
			Date updatedAt) {
		this.userName = userName;
		this.productCode = productCode;
		this.rating = rating;
		this.message = message;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public short getRating() {
		return this.rating;
	}

	public void setRating(short rating) {
		this.rating = rating;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getProductCode() {
		return productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	

}
